controller_server:
  ros__parameters:
    controller_frequency: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

costmap_common:
  ros__parameters:
    inflation_radius: 0.5
    obstacle_range: 2.5
    raytrace_range: 3.0

local_costmap:
  ros__parameters:
    global_frame: "odom"
    robot_base_frame: "base_link"

global_costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
