 
controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    max_vel_x: 0.5
    max_rotational_vel: 1.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0

behavior_server:
  ros__parameters:
    behavior_plugins: ["spin", "backup", "assisted_teleop"]
